apiVersion: argoproj.io/v1alpha1
kind: Workflow
metadata:
  generateName: swgs-stl-rl245nx1g1
spec:
  entrypoint: enterpoint
  hostNetwork: true
  volumes:
  - name: output
    nfs :
      path: /NAS/CAPFS/data/sxyf_keyan/01.yanfa/11.hWGS.cut/00.update_results/sWGS/01.do
      server: nas0.h3c.fanshengzi.com
  - name: script
    nfs :
      path: /NAS/CAPFS/data/sxyf_keyan/01.yanfa/25.database_and_script/Script
      server: nas0.h3c.fanshengzi.com
  - name: database
    nfs :
      path: /NAS/CAPFS/data/sxyf_keyan/01.yanfa/25.database_and_script/DataBase
      server: nas0.h3c.fanshengzi.com
 
  templates:
  - name: enterpoint
    dag :
      tasks :
        - name : bigbed
          template: bigbed
    
  
  - name: bigbed
    container:
      image: registry-vpc.cn-beijing.aliyuncs.com/fsz_base/zaoshai_localk8s_aliyun:v1.2
      imagePullPolicy: IfNotPresent
      command: ["/bin/bash","-c"]
      args: ["
        echo \"one of six : start CPG\" &&
        python /program/mole.py -gbam  /Output/RL245NX1g1/RL245NX1g1_GC_relate.sort.bam -mbam /Output/RL245NX1g1/RL245NX1g1_GC.sort.bam -b /Script/CPG_island_start_end_rmXY.bed -s RL245NX1g1 -o /Output/RL245NX1g1/RL245NX1g1_cpg.xls -k cpg -t 8 &&
        echo \"two of six : start promoter\" &&
        python /program/mole.py -gbam  /Output/RL245NX1g1/RL245NX1g1_GC_relate.sort.bam -mbam /Output/RL245NX1g1/RL245NX1g1_GC.sort.bam -b /Script/gene_promoter.bed -s RL245NX1g1 -o /Output/RL245NX1g1/RL245NX1g1_promoter.xls -k promoter -t 8 &&
        echo \"three of six : start promoter+first exon\" &&
        python /program/mole.py -gbam  /Output/RL245NX1g1/RL245NX1g1_GC_relate.sort.bam -mbam /Output/RL245NX1g1/RL245NX1g1_GC.sort.bam -b /Script/gene_promoter_fexon.bed -s RL245NX1g1 -o /Output/RL245NX1g1/RL245NX1g1_promoter.fexon.xls -k promoter.fexon -t 8 &&
        echo \"four of six : start panel825\" &&
        python /program/mole.py -gbam  /Output/RL245NX1g1/RL245NX1g1_GC_relate.sort.bam -mbam /Output/RL245NX1g1/RL245NX1g1_GC.sort.bam -b /Script/panel825-63_promoter_Eexon.bed -s RL245NX1g1 -o /Output/RL245NX1g1/RL245NX1g1_panel825-63_promoter_Eexon.xls -k panel825-63_promoter_Eexon -t 8 &&
        echo \"five of six : start panel 831 +rm intron\" &&
        python /program/mole.py -gbam  /Output/RL245NX1g1/RL245NX1g1_GC_relate.sort.bam -mbam /Output/RL245NX1g1/RL245NX1g1_GC.sort.bam -b /Script/panel825-63_promoter_exon_rmintron.bed -s RL245NX1g1 -o /Output/RL245NX1g1/RL245NX1g1_panel831_rmintron.xls -k panel831_rmintron -t 8 &&
        echo \"six of six : start genebody\" &&
        python /program/mole.py -gbam  /Output/RL245NX1g1/RL245NX1g1_GC_relate.sort.bam -mbam /Output/RL245NX1g1/RL245NX1g1_GC.sort.bam -b /Script/hg19_gene_body.bed -s RL245NX1g1 -o /Output/RL245NX1g1/RL245NX1g1_genebody.xls -k genebody -t 8 &&
        rm /Output/RL245NX1g1/*.bam /Output/RL245NX1g1/*.bam.bai
      "]
      resources:
        requests:
          memory: 5Gi
          cpu: 3000m
        limits:
          memory: 32Gi
          cpu: 16000m
      volumeMounts:
      - name: output
        mountPath: /Output
      - name: script
        mountPath: /Script
      - name: database
        mountPath: /Database
